name: Update API Data

on:
  schedule:
    - cron: '0 22 * * *'  # Spustí se každý den ve 22:00 UTC (půlnoc CEST)
  workflow_dispatch:  # Umožní manuální spuštění

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Generate API data
      run: node src/generate-data.js
    - name: Commit and push if changed
      run: |
        git config --global user.name 'patekcz'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add public/api-data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Aktualizace API dat" && git push)
