name: Update API Data

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-data:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: List directory contents
      run: ls -R
    
    - name: Check file existence
      run: |
        [ -f src/generate-data.js ] && echo "generate-data.js exists" || echo "generate-data.js not found"
        [ -f src/data/date.json ] && echo "date.json exists" || echo "date.json not found"
    
    - name: Check date and timezone
      run: |
        date
        echo $TZ
    
    - name: Generate API data
      run: |
        mkdir -p public
        node src/generate-data.js
    
    - name: Check generated file
      run: |
        [ -f public/api-data.json ] && echo "api-data.json exists" && cat public/api-data.json || echo "api-data.json not found"
    
    - name: Push generated data to output branch
      run: |
        git config --global user.name 'patekcz'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add public/api-data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Aktualizace API dat" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
