name: Update API Data

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: List directory contents
      run: ls -R
    - name: Check file existence
      run: |
        [ -f src/generate-data.js ] && echo "generate-data.js exists" || echo "generate-data.js not found"
        [ -f src/data/date.json ] && echo "date.json exists" || echo "date.json not found"
    - name: Generate API data
      run: node src/generate-data.js
    - name: Commit and push if changed
      run: |
        git config --global user.name 'patekcz'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add public/api-data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Aktualizace API dat" && git push)
